{% set name = "pymove" %}
{% set version = "2.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d1e9cfb2c5befc1c46d16b79ff7efb9e8f429ed48e83e1e93807ace2bef03586

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - branca
    - dask
    - folium >=0.10.1
    - geohash2
    - geojson
    - holidays
    - ipython
    - ipywidgets
    - joblib
    - matplotlib-base
    - mplleaflet
    - numpy
    - pandas <=1.0.5
    - psutil
    - python >=3.6
    - pytz
    - scikit-learn
    - scipy
    - shapely
    - tqdm

test:
  requires:
    - pytest
    - geopandas
  commands:
    - pytest --pyargs pymove

about:
  home: https://github.com/InsightLab/PyMove
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: A lib python to processing and visualization of trajectories and other spatial-temporal data
  doc_url: https://pymove.readthedocs.io/en/latest/
  dev_url:

extra:
  recipe-maintainers:
    - flych3r
